//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMateriales.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class AceroGMaquinaria
    {
        public int idMaterial { get; set; }
        public string Calidad { get; set; }
        public string Perfil { get; set; }
        public string Acabado { get; set; }
        public string Medidas { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
