//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMateriales.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metales
    {
        public int idMaterial { get; set; }
        public string Mineral { get; set; }
        public string MateriaPrima { get; set; }
        public string SemiFabricado { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
