//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSMateriales.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataMasterEntities : DbContext
    {
        public DataMasterEntities()
            : base("name=DataMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AceroGHerramienta> AceroGHerramienta { get; set; }
        public virtual DbSet<AceroGMaquinaria> AceroGMaquinaria { get; set; }
        public virtual DbSet<AceroInoxidable> AceroInoxidable { get; set; }
        public virtual DbSet<Metales> Metales { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
